/**
 * Migration-test harness: verify that a user's persisted data (workspaces,
 * sessions, durable titles) written by one release opens intact under a fresh
 * instance of the current release — the A→B upgrade safety check.
 *
 * Honesty note (pre-release): there is no prior released artifact to upgrade
 * FROM yet, so the "release A" data is generated by the current release's own
 * runtime/UI (the same on-disk format a prior release would have written). The
 * harness is what a true cross-artifact A→B check will run: it takes an
 * EXISTING `DSH_HOME` and asserts its data is intact under the current build.
 * Point {@link verifyMigratedData} at a real prior-release user-data dir once
 * one ships. See the Stage 12 migration readiness doc for the contract.
 *
 * The harness talks to the UI only through the surfaces a user does (composer,
 * sidebar, the rename dialog) and reads durable state through the on-disk logs
 * and the transport — never a backdoor. It does not import vitest's `expect`;
 * the spec asserts.
 */
import { existsSync, mkdirSync, mkdtempSync, rmSync } from 'node:fs'
import { realpath } from 'node:fs/promises'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import type { ElectronApplication, Page } from 'playwright'
import { _electron as electron } from 'playwright'
import {
  acknowledgeFirstRun,
  awaitDurableTitle,
  composerEditable,
  openSidebar,
  rpc,
  seedWorkspaceRegistry,
  waitForShellReady,
  type SessionSummary,
} from './electron-world.ts'
import type { ScriptedProvider } from './deterministic-provider.ts'

const appDir = join(import.meta.dirname, '..', '..')

/** The durable facts a migration must preserve. */
export interface MigrationFixture {
  /** The user-data dir (the profile). */
  userData: string
  /** The harness home the desktop derives from the profile. */
  home: string
  /** The workspace directory the fixture data lives under. */
  workspaceDir: string
  /** The workspace's registry title. */
  workspaceTitle: string
  /** A unique marker the streamed turn rendered (content integrity). */
  streamMarker: string
  /** A unique marker the tool turn rendered. */
  toolMarker: string
  /** The file the tool wrote into the workspace (world-state integrity). */
  toolFile: string
  /** The user-set durable session title (the rename). */
  durableTitle: string
}

/** A bounded poll (the support module does not import vitest's `expect`). */
async function pollUntil(predicate: () => Promise<boolean>, timeoutMs: number, what: string): Promise<void> {
  const deadline = Date.now() + timeoutMs
  for (;;) {
    if (await predicate()) return
    if (Date.now() > deadline) throw new Error(`timed out after ${String(timeoutMs)}ms waiting for ${what}`)
    await new Promise(resolveWait => setTimeout(resolveWait, 200))
  }
}

/**
 * Generate the "release A" user data: boot the current app at a fresh profile,
 * seed a workspace, run a stream + a tool turn (real content), rename the
 * session, and quit cleanly. The on-disk result is the fixture's data.
 * @param provider - the deterministic loopback model the turns reach.
 * @param work - a temp root the profile and workspace are created under.
 * @param autoTitle - the auto-generated session title the provider returns
 *   (the label the session row shows before the rename).
 */
export async function createMigrationFixture(provider: ScriptedProvider, work: string, autoTitle: string): Promise<MigrationFixture> {
  const userData = join(work, 'migrated-user-data')
  const home = join(userData, 'harness')
  mkdirSync(join(work, 'mig-ws'), { recursive: true })
  const workspaceDir = await realpath(join(work, 'mig-ws'))
  const workspaceTitle = 'migrated-workspace'
  const toolFile = 'migrated-out.txt'
  seedWorkspaceRegistry(home, workspaceDir, workspaceTitle, 'ws-migrated')

  const app: ElectronApplication = await electron.launch({
    args: [appDir, `--user-data-dir=${userData}`],
    env: { ...process.env, DEEPSEEK_API_KEY: 'keyless-migration', DEEPSEEK_BASE_URL: provider.url },
  })
  try {
    const win = await app.firstWindow()
    await win.waitForLoadState('domcontentloaded')
    await waitForShellReady(win)
    await acknowledgeFirstRun(win)
    await pollUntil(() => composerEditable(win), 60_000, 'the composer to become editable')
    const composer = win.locator('[data-composer-card] textarea')
    await composer.fill('migration stream turn')
    await composer.press('Enter')
    await pollUntil(async () => win.evaluate(() => document.body.innerText.includes('MIGRATION_STREAM_DONE')), 60_000, 'the streamed turn to render')
    await composer.fill('migration tool turn')
    await composer.press('Enter')
    await pollUntil(async () => win.evaluate(() => document.body.innerText.includes('MIGRATION_TOOL_DONE')), 60_000, 'the tool turn to render')
    // Rename the session: the durable title a migration must carry.
    await renameSession(win, autoTitle, 'Migrated final title')
    await awaitDurableTitle(home, 'Migrated final title', 'user', 15_000)
  } finally {
    await app.close()
  }
  return {
    userData,
    home,
    workspaceDir,
    workspaceTitle,
    streamMarker: 'MIGRATION_STREAM_DONE',
    toolMarker: 'MIGRATION_TOOL_DONE',
    toolFile,
    durableTitle: 'Migrated final title',
  }
}

/** Drive the row's Rename affordance through the session row menu. */
async function renameSession(win: Page, currentTitle: string, newTitle: string): Promise<void> {
  await openSidebar(win)
  const row = win.locator(`[role="treeitem"]:has(> span:has(button[aria-label="Session actions for ${currentTitle}"]))`)
  await row.first().waitFor({ timeout: 30_000 })
  await row.first().hover()
  await row.locator('button[aria-label^="Session actions for"]').first().click()
  await win.getByRole('menuitem', { name: 'Rename' }).click()
  const dialog = win.getByRole('dialog')
  await dialog.waitFor({ timeout: 10_000 })
  await dialog.locator('input[aria-label="Session name"]').fill(newTitle)
  await dialog.getByRole('button', { name: 'Rename' }).click()
  await win.locator('[role="treeitem"]').filter({ hasText: newTitle }).first().waitFor({ timeout: 15_000 })
}

export interface MigrationVerification {
  sessions: SessionSummary[]
  /** 0 when the first-run acknowledgement persisted across the upgrade. */
  firstRunCount: number
  workspaceListed: boolean
  titleOnColdList: boolean
  contentReplayed: boolean
}

/**
 * Verify an EXISTING user-data dir (release A) opens intact under a fresh
 * instance of the current release (release B): the workspace is listed, the
 * session survives with its durable title, and reopening it replays the
 * recorded content. Pass a real prior-release profile's `userData` to run the
 * true cross-artifact check.
 */
export async function verifyMigratedData(userData: string, fixture: Pick<MigrationFixture, 'streamMarker' | 'toolMarker' | 'durableTitle' | 'workspaceTitle'>): Promise<MigrationVerification> {
  const app: ElectronApplication = await electron.launch({
    args: [appDir, `--user-data-dir=${userData}`],
    env: { ...process.env, DEEPSEEK_API_KEY: 'keyless-migration-verify', DEEPSEEK_BASE_URL: process.env.DEEPSEEK_BASE_URL ?? 'http://127.0.0.1:9' },
  })
  try {
    const win = await app.firstWindow()
    await win.waitForLoadState('domcontentloaded')
    await waitForShellReady(win)
    // The first-run acknowledgement persisted across the "upgrade" (a fresh
    // profile would show the welcome notice; an upgraded one must not).
    const firstRunCount = await win.getByRole('button', { name: 'Continue' }).count()
    await pollUntil(() => composerEditable(win), 60_000, 'the composer to become editable on the upgraded profile')
    const listed = await rpc<{ items: SessionSummary[] }>(win, 'session.list', {}, 'migration-verify')
    const sessions = listed.items
    const workspaces = await rpc<{ items: Array<{ title?: string }> }>(win, 'workspace.list', {}, 'migration-verify-ws')
    const workspaceListed = workspaces.items.some(item => item.title === fixture.workspaceTitle)
    const titleOnColdList = sessions.some(item => item.projections?.values.title === fixture.durableTitle)
    // Reopen the session: its recorded content replays.
    await openSidebar(win)
    const sessionRow = win.locator('[role="treeitem"]').filter({ hasText: fixture.durableTitle }).first()
    let contentReplayed = false
    if (await sessionRow.count() > 0) {
      await sessionRow.click()
      contentReplayed = await pollUntil(
        async () => win.evaluate(probe => document.body.innerText.includes(probe), fixture.streamMarker),
        40_000,
        'the streamed content to replay',
      ).then(() => true).catch(() => false)
    }
    return { sessions, firstRunCount, workspaceListed, titleOnColdList, contentReplayed }
  } finally {
    await app.close()
  }
}

/** Remove a generated profile's temp work dir. */
export function cleanupWork(work: string): void {
  rmSync(work, { recursive: true, force: true })
}

/** A fresh temp work root for a migration run. */
export function newWorkRoot(prefix: string): string {
  return mkdtempSync(join(tmpdir(), prefix))
}

/** Whether the fixture's world-state file survived (checked by the spec). */
export function toolFileExists(fixture: MigrationFixture): boolean {
  return existsSync(join(fixture.workspaceDir, fixture.toolFile))
}
